numpy: numerical python

In [3]:
!pip install numpy

     --------------------------------------- 12.9/12.9 MB 19.8 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
lst2 = []
for i in lst:
    lst2.append(i+1)

In [5]:
lst2

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [6]:
%timeit [i**2 for i in lst]

939 ns ± 199 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


we can perform fast calculations:


In [7]:
vectorization: it will be performing all operations directly on elements


SyntaxError: invalid syntax (2726178334.py, line 1)

In [ ]:
arr = np.array(lst)

In [ ]:
type(lst)

In [ ]:
type(arr)

In [ ]:
arr.ndim

In [ ]:
arr + 1

In [ ]:
#lst +1 not possible but it s possible in array:


In [ ]:
arr**2

In [ ]:
[i**2 for i in lst]

In [ ]:
Numpy Basics:

In [ ]:
#arr = np.array()
# arr = np.arange()


In [ ]:
lst3 = list(range(1,10))

In [ ]:
lst3

In [ ]:
arr3

In [ ]:
arr3 = np.array(lst3)

In [ ]:
type(arr3)

In [ ]:
arr3.ndim

In [ ]:
arr3.dtype

In [ ]:
arr4 = np.arange(1,15)

In [ ]:
arr4

In [ ]:
type(arr4)

In [ ]:
arr4.shape

In [ ]:
list(range(1,20))

In [ ]:
arr3.shape

In [ ]:
arr3.ndim

In [ ]:
lst2d = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
lst2d

In [ ]:
arr5 = np.array(lst2d)

In [ ]:
arr5

In [ ]:
arr5.ndim

In [ ]:
arr5.dtype

In [ ]:
arr5.shape

In [ ]:
some special arrays in numpy;
#zeros
#ones()
#diaganol()
#identity()


In [ ]:
np.zeros(5)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((3,4))

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,3))

In [ ]:
np.diag([5])

In [ ]:
np.diag([1,2,3,4,4,5])

In [ ]:
np.identity(4)

In [ ]:
np.identity(6)

In [ ]:
np.eye(3)

#stacking
vstack
hstack

transpose: converting our rows into columns and columns into rows

In [ ]:
arr1= np.arange(0,2)

In [ ]:
arr1

In [ ]:
arr2 = np.arange(0,12)

In [ ]:
arr2

In [ ]:
arr3=np.arange(4,20)

In [ ]:
arr3

In [ ]:
A = np.random.randint(0,10,size=(3,3))

In [ ]:
B= np.array([1,2,3])

In [ ]:
A

In [ ]:
B

In [ ]:
A.shape

In [ ]:
A +B

In [ ]:
A.T + B

vectorization: it will be performing all operations directly on elements

In [ ]:
total = 0 
for i in range(len(p)):
    total += (q[i]-p[i])**2

In [ ]:
p = [1,2,3,4,5,-6,7,8]
q = [9,9,6,7,5,-4,3,2]

In [ ]:
p = np.array(p)

In [ ]:
q = np.array(q)

In [ ]:
arr6 = np.array(lst2d)

In [ ]:
arr6

In [ ]:
arr7= np.random.randint(0,20,(8,6))

In [ ]:
arr7

In [ ]:
arr7

In [ ]:
arr7=[5:7,4:6]

In [ ]:
arr7[4]

In [ ]:
arr7[-2]

In [ ]:
arr7[-2:]

In [ ]:
arr7[5:7,1:3]

In [ ]:
arr7=[6:7,2:1]

In [ ]:
arr7

In [ ]:
arr7[5:7,2:4]

In [ ]:
arr7[5:7,4:6]

In [ ]:
arr7

In [ ]:
arr7[-3:-1,-2:]

#masking : boolean indexing : true,false

In [ ]:
arr5>11

In [ ]:
arr7==0

In [ ]:
arr7[arr7>10]

#basic oprations 

In [ ]:
a = np.array([10,20,30,40])

In [ ]:
 b = np.array([1,2,3,4])

In [ ]:
c= a+b

In [ ]:
c

In [ ]:
6

In [12]:
arr8=np.random.randint(0,20,(8,6))

In [13]:
arr8

array([[ 0,  7, 10,  9,  8,  5],
       [11, 14,  6, 13,  6,  6],
       [ 4, 12,  8, 12,  4,  8],
       [16, 16,  1, 16,  3, 18],
       [16, 15, 18,  9,  8, 17],
       [ 1,  3, 12, 11, 12, 14],
       [ 8,  5,  4,  8, 16, 17],
       [ 1,  1, 14,  3,  9, 13]], dtype=int32)

In [14]:
arr8[:,-1]

array([ 5,  6,  8, 18, 17, 14, 17, 13], dtype=int32)

In [15]:
arr8[:,0]

array([ 0, 11,  4, 16, 16,  1,  8,  1], dtype=int32)

In [16]:
arr8[-3:-5,-1:-3]

array([], shape=(0, 0), dtype=int32)

In [18]:
arr8[:-2]

array([[ 0,  7, 10,  9,  8,  5],
       [11, 14,  6, 13,  6,  6],
       [ 4, 12,  8, 12,  4,  8],
       [16, 16,  1, 16,  3, 18],
       [16, 15, 18,  9,  8, 17],
       [ 1,  3, 12, 11, 12, 14]], dtype=int32)

In [19]:
arr8[-3:,-3:]

array([[11, 12, 14],
       [ 8, 16, 17],
       [ 3,  9, 13]], dtype=int32)

In [20]:
arr8

array([[ 0,  7, 10,  9,  8,  5],
       [11, 14,  6, 13,  6,  6],
       [ 4, 12,  8, 12,  4,  8],
       [16, 16,  1, 16,  3, 18],
       [16, 15, 18,  9,  8, 17],
       [ 1,  3, 12, 11, 12, 14],
       [ 8,  5,  4,  8, 16, 17],
       [ 1,  1, 14,  3,  9, 13]], dtype=int32)

In [22]:
arr8[:-1]

array([[ 0,  7, 10,  9,  8,  5],
       [11, 14,  6, 13,  6,  6],
       [ 4, 12,  8, 12,  4,  8],
       [16, 16,  1, 16,  3, 18],
       [16, 15, 18,  9,  8, 17],
       [ 1,  3, 12, 11, 12, 14],
       [ 8,  5,  4,  8, 16, 17]], dtype=int32)

In [23]:
arr8[:,0]

array([ 0, 11,  4, 16, 16,  1,  8,  1], dtype=int32)

In [24]:
arr8[:,-1]

array([ 5,  6,  8, 18, 17, 14, 17, 13], dtype=int32)

In [25]:
arr8[:,5]

array([ 5,  6,  8, 18, 17, 14, 17, 13], dtype=int32)

In [26]:
arr8

array([[ 0,  7, 10,  9,  8,  5],
       [11, 14,  6, 13,  6,  6],
       [ 4, 12,  8, 12,  4,  8],
       [16, 16,  1, 16,  3, 18],
       [16, 15, 18,  9,  8, 17],
       [ 1,  3, 12, 11, 12, 14],
       [ 8,  5,  4,  8, 16, 17],
       [ 1,  1, 14,  3,  9, 13]], dtype=int32)

#masking: boolean indexing:True ,false

In [27]:
arr8>10

array([[False, False, False, False, False, False],
       [ True,  True, False,  True, False, False],
       [False,  True, False,  True, False, False],
       [ True,  True, False,  True, False,  True],
       [ True,  True,  True, False, False,  True],
       [False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False,  True, False, False,  True]])

In [28]:
arr8>150

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [29]:
arr8[arr8>15]

array([16, 16, 16, 18, 16, 18, 17, 16, 17], dtype=int32)

In [32]:
p=np.random.randint(0,20,(8,6))

In [33]:
q=np.random.randint(0,20,(6,8))

In [34]:
np.dot(p,q)

array([[596, 534, 506, 661, 674, 219, 364, 672],
       [485, 507, 563, 365, 479,  75, 268, 574],
       [386, 495, 394, 253, 437,  73, 344, 451],
       [693, 698, 797, 871, 828, 201, 767, 749],
       [431, 435, 567, 712, 555, 136, 612, 474],
       [602, 531, 700, 533, 739, 179, 470, 643],
       [562, 552, 454, 598, 689, 218, 534, 576],
       [424, 450, 343, 353, 484, 132, 401, 420]], dtype=int32)

In [37]:
r=np.arange(0,24)

In [38]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
r.shape

(24,)

In [45]:
arr9=r.reshape(8,3)

In [41]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
r.reshape(10,5)

ValueError: cannot reshape array of size 24 into shape (10,5)

In [43]:
r.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
np.sum(arr9)

np.int64(276)

In [48]:
np.sum(arr9,axis=0) #coloumn wise sum

array([ 84,  92, 100])

In [49]:
np.sum(arr9,axis=1) #row wise sum

array([ 3, 12, 21, 30, 39, 48, 57, 66])

In [50]:
arr9.min()

np.int64(0)

In [51]:
arr9.max()

np.int64(23)

In [52]:
arr9.max(axis=0)

array([21, 22, 23])

In [53]:
arr9.mean(axis=0)

array([10.5, 11.5, 12.5])

In [54]:
arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [55]:
np.sqrt(arr9)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563],
       [4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152]])

In [56]:
np.square(arr9)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289],
       [324, 361, 400],
       [441, 484, 529]])